package org.yafra.orm.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.yafra.orm.Person;

/**
 * Class _PersonLog was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PersonLog extends CayenneDataObject {

    public static final String EVENT_AUDIT_PROPERTY = "eventAudit";
    public static final String EVENT_AUDIT_REVIEWER_PROPERTY = "eventAuditReviewer";
    public static final String EVENT_CREATOR_PROPERTY = "eventCreator";
    public static final String EVENT_DATE_PROPERTY = "eventDate";
    public static final String EVENT_DESCRIPTION_PROPERTY = "eventDescription";
    public static final String TO_PERSON_PROPERTY = "toPerson";

    public static final String PK_PERSON_LOG_PK_COLUMN = "pkPersonLog";

    public void setEventAudit(String eventAudit) {
        writeProperty(EVENT_AUDIT_PROPERTY, eventAudit);
    }
    public String getEventAudit() {
        return (String)readProperty(EVENT_AUDIT_PROPERTY);
    }

    public void setEventAuditReviewer(String eventAuditReviewer) {
        writeProperty(EVENT_AUDIT_REVIEWER_PROPERTY, eventAuditReviewer);
    }
    public String getEventAuditReviewer() {
        return (String)readProperty(EVENT_AUDIT_REVIEWER_PROPERTY);
    }

    public void setEventCreator(String eventCreator) {
        writeProperty(EVENT_CREATOR_PROPERTY, eventCreator);
    }
    public String getEventCreator() {
        return (String)readProperty(EVENT_CREATOR_PROPERTY);
    }

    public void setEventDate(Date eventDate) {
        writeProperty(EVENT_DATE_PROPERTY, eventDate);
    }
    public Date getEventDate() {
        return (Date)readProperty(EVENT_DATE_PROPERTY);
    }

    public void setEventDescription(String eventDescription) {
        writeProperty(EVENT_DESCRIPTION_PROPERTY, eventDescription);
    }
    public String getEventDescription() {
        return (String)readProperty(EVENT_DESCRIPTION_PROPERTY);
    }

    public void setToPerson(Person toPerson) {
        setToOneTarget(TO_PERSON_PROPERTY, toPerson, true);
    }

    public Person getToPerson() {
        return (Person)readProperty(TO_PERSON_PROPERTY);
    }


}
