package org.yafra.orm.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.yafra.orm.PersonLog;

/**
 * Class _Person was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Person extends CayenneDataObject {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String COUNTRY_PROPERTY = "country";
    public static final String FIRSTNAME_PROPERTY = "firstname";
    public static final String GOOGLE_ID_PROPERTY = "googleId";
    public static final String ID_PROPERTY = "id";
    public static final String NAME_PROPERTY = "name";
    public static final String TYPE_PROPERTY = "type";
    public static final String LOG_ARRAY_PROPERTY = "logArray";

    public static final String PK_PERSON_PK_COLUMN = "pkPerson";

    public void setAddress(String address) {
        writeProperty(ADDRESS_PROPERTY, address);
    }
    public String getAddress() {
        return (String)readProperty(ADDRESS_PROPERTY);
    }

    public void setCountry(String country) {
        writeProperty(COUNTRY_PROPERTY, country);
    }
    public String getCountry() {
        return (String)readProperty(COUNTRY_PROPERTY);
    }

    public void setFirstname(String firstname) {
        writeProperty(FIRSTNAME_PROPERTY, firstname);
    }
    public String getFirstname() {
        return (String)readProperty(FIRSTNAME_PROPERTY);
    }

    public void setGoogleId(String googleId) {
        writeProperty(GOOGLE_ID_PROPERTY, googleId);
    }
    public String getGoogleId() {
        return (String)readProperty(GOOGLE_ID_PROPERTY);
    }

    public void setId(Integer id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setType(String type) {
        writeProperty(TYPE_PROPERTY, type);
    }
    public String getType() {
        return (String)readProperty(TYPE_PROPERTY);
    }

    public void addToLogArray(PersonLog obj) {
        addToManyTarget(LOG_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromLogArray(PersonLog obj) {
        removeToManyTarget(LOG_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PersonLog> getLogArray() {
        return (List<PersonLog>)readProperty(LOG_ARRAY_PROPERTY);
    }


}
