package org.yafra.orm.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.yafra.orm.YafraUser;

/**
 * Class _YafraUserDevice was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _YafraUserDevice extends CayenneDataObject {

    public static final String DEVICE_AUTH_DATE_PROPERTY = "deviceAuthDate";
    public static final String DEVICE_AUTH_TOKEN_PROPERTY = "deviceAuthToken";
    public static final String DEVICE_ID_PROPERTY = "deviceId";
    public static final String DEVICE_OS_PROPERTY = "deviceOs";
    public static final String DEVICE_PUSH_TOKEN_PROPERTY = "devicePushToken";
    public static final String DEVICE_REGISTRATION_DATE_PROPERTY = "deviceRegistrationDate";
    public static final String TO_YAFRA_USER_PROPERTY = "toYafraUser";

    public static final String PK_YAFRA_USER_DEVICE_PK_COLUMN = "pkYafraUserDevice";

    public void setDeviceAuthDate(Date deviceAuthDate) {
        writeProperty(DEVICE_AUTH_DATE_PROPERTY, deviceAuthDate);
    }
    public Date getDeviceAuthDate() {
        return (Date)readProperty(DEVICE_AUTH_DATE_PROPERTY);
    }

    public void setDeviceAuthToken(String deviceAuthToken) {
        writeProperty(DEVICE_AUTH_TOKEN_PROPERTY, deviceAuthToken);
    }
    public String getDeviceAuthToken() {
        return (String)readProperty(DEVICE_AUTH_TOKEN_PROPERTY);
    }

    public void setDeviceId(String deviceId) {
        writeProperty(DEVICE_ID_PROPERTY, deviceId);
    }
    public String getDeviceId() {
        return (String)readProperty(DEVICE_ID_PROPERTY);
    }

    public void setDeviceOs(String deviceOs) {
        writeProperty(DEVICE_OS_PROPERTY, deviceOs);
    }
    public String getDeviceOs() {
        return (String)readProperty(DEVICE_OS_PROPERTY);
    }

    public void setDevicePushToken(String devicePushToken) {
        writeProperty(DEVICE_PUSH_TOKEN_PROPERTY, devicePushToken);
    }
    public String getDevicePushToken() {
        return (String)readProperty(DEVICE_PUSH_TOKEN_PROPERTY);
    }

    public void setDeviceRegistrationDate(Date deviceRegistrationDate) {
        writeProperty(DEVICE_REGISTRATION_DATE_PROPERTY, deviceRegistrationDate);
    }
    public Date getDeviceRegistrationDate() {
        return (Date)readProperty(DEVICE_REGISTRATION_DATE_PROPERTY);
    }

    public void setToYafraUser(YafraUser toYafraUser) {
        setToOneTarget(TO_YAFRA_USER_PROPERTY, toYafraUser, true);
    }

    public YafraUser getToYafraUser() {
        return (YafraUser)readProperty(TO_YAFRA_USER_PROPERTY);
    }


}
