package org.yafra.orm.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.yafra.orm.YafraRole;
import org.yafra.orm.YafraUser;

/**
 * Class _YafraBusinessRole was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _YafraBusinessRole extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String FLAG_PROPERTY = "flag";
    public static final String NAME_PROPERTY = "name";
    public static final String YUSERS_PROPERTY = "YUsers";
    public static final String TECHNICAL_ROLES_ARRAY_PROPERTY = "technicalRolesArray";

    public static final String PK_YAFRA_BUSINESS_ROLE_PK_COLUMN = "pkYafraBusinessRole";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setFlag(Boolean flag) {
        writeProperty(FLAG_PROPERTY, flag);
    }
    public Boolean getFlag() {
        return (Boolean)readProperty(FLAG_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToYUsers(YafraUser obj) {
        addToManyTarget(YUSERS_PROPERTY, obj, true);
    }
    public void removeFromYUsers(YafraUser obj) {
        removeToManyTarget(YUSERS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<YafraUser> getYUsers() {
        return (List<YafraUser>)readProperty(YUSERS_PROPERTY);
    }


    public void addToTechnicalRolesArray(YafraRole obj) {
        addToManyTarget(TECHNICAL_ROLES_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromTechnicalRolesArray(YafraRole obj) {
        removeToManyTarget(TECHNICAL_ROLES_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<YafraRole> getTechnicalRolesArray() {
        return (List<YafraRole>)readProperty(TECHNICAL_ROLES_ARRAY_PROPERTY);
    }


}
